---
- name: Install Gitea
  ansible.builtin.import_tasks: install.yml
  tags:
    - gitea_install

- name: Configure Gitea admin
  ansible.builtin.import_tasks: admin.yml
  tags:
    - gitea_admin

- name: Configure Gitea Actions runner
  ansible.builtin.import_tasks: runner.yml
  tags:
    - gitea_runner
