"all":
  "children":
    "docker_hosts":
      "hosts":
        "dns02": {}
        "gitea": {}
        "packer_builder": {}
    "terraform_created":
      "children":
        "almalinux":
          "hosts":
            "dns02":
              "ansible_host": "10.37.70.254"
              "system_hostname": "dns02"
            "gitea":
              "ansible_host": "10.37.80.4"
              "system_hostname": null
            "packer_builder":
              "ansible_host": "10.37.80.5"
              "system_hostname": "packer-builder"
