"all":
  "children":
    "docker_hosts":
      "hosts":
        "gitea": {}
        "labtest": {}
    "terraform_created":
      "children":
        "almalinux":
          "hosts":
            "gitea":
              "ansible_host": "10.37.80.4"
              "system_hostname": null
            "labtest":
              "ansible_host": "10.37.70.41"
              "system_hostname": null
