name: inventory-sync

on:
  workflow_run:
    workflows: ["orchestrate-push"]
    types: ["completed"]
  push:
    branches: ["main"]

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          dnf -y module enable nodejs:20 || true
          dnf -y install unzip curl jq git ca-certificates tar which nodejs

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Terraform
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o /tmp/terraform.zip
          unzip -o /tmp/terraform.zip -d /usr/local/bin

      - name: Sync inventories (lab & prod)
        id: sync_all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-005
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          set -euo pipefail
          UPDATED=0
          for ENV in lab prod; do
            echo "--- Processing $ENV ---"
            TF_DIR="terraform/envs/$ENV"
            if [ ! -d "$TF_DIR" ]; then
              echo "Skipping $ENV: directory $TF_DIR not found"; continue
            fi
            # Init backend for CI: always use backend.hcl with CI-provided AWS_* secrets; never use backend.s3.secrets.hcl in CI
            if [ -f "$TF_DIR/backend.hcl" ]; then
              terraform -chdir="$TF_DIR" init -backend-config=backend.hcl -reconfigure -input=false >/dev/null
            else
              # For lab or local-only envs without backend.hcl, initialize without backend
              terraform -chdir="$TF_DIR" init -backend=false -input=false >/dev/null
            fi
            INV_DIR="ansible/inventories/$ENV"
            INV_FILE="$INV_DIR/hosts.yml"
            mkdir -p "$INV_DIR"
            TMP=$(mktemp)
            if terraform -chdir="$TF_DIR" output -raw ansible_inventory_yaml > "$TMP" 2>/dev/null; then
              if [ ! -f "$INV_FILE" ] || ! cmp -s "$INV_FILE" "$TMP"; then
                mv "$TMP" "$INV_FILE"
                echo "Updated inventory for $ENV"
                UPDATED=1
              else
                rm -f "$TMP"
                echo "No changes for $ENV"
              fi
            else
              rm -f "$TMP"
              echo "Output ansible_inventory_yaml not found for $ENV; skipping"
            fi
          done
          echo "UPDATED=$UPDATED" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.sync_all.outputs.UPDATED == '1'
        env:
          GIT_AUTHOR_NAME: ci-bot
          GIT_AUTHOR_EMAIL: ci-bot@local
          GIT_COMMITTER_NAME: ci-bot
          GIT_COMMITTER_EMAIL: ci-bot@local
        run: |
          set -euo pipefail
          git add ansible/inventories
          git commit -m "Inventory sync: lab & prod"
          git push
