name: orchestrate-dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (lab|prod)"
        required: true
        default: "lab"
      action:
        description: "terraform action (plan|apply)"
        required: true
        default: "plan"
      build_packer:
        description: "Build Packer template first (true|false)"
        required: true
        default: "false"

jobs:
  validate:
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          # Ensure Node.js is present for JavaScript-based actions (actions/checkout)
          dnf -y module enable nodejs:20 || true
          dnf -y install unzip curl jq git openssh-clients ca-certificates tar which nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o /tmp/terraform.zip
          unzip -o /tmp/terraform.zip -d /usr/local/bin
          terraform -version

      - name: Terraform fmt/validate (lab)
        run: |
          terraform -chdir=terraform/envs/lab init -backend=false
          terraform -chdir=terraform/envs/lab fmt -check
          terraform -chdir=terraform/envs/lab validate

      - name: Terraform fmt/validate (prod)
        run: |
          terraform -chdir=terraform/envs/prod init -backend=false
          terraform -chdir=terraform/envs/prod fmt -check
          terraform -chdir=terraform/envs/prod validate

  packer-build:
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    needs: [validate]
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          # Ensure Node.js is present for JavaScript-based actions (actions/checkout)
          dnf -y module enable nodejs:20 || true
          dnf -y install unzip curl jq git openssh-clients ca-certificates tar which nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip -o /tmp/packer.zip
          unzip -o /tmp/packer.zip -d /usr/local/bin

      - name: Respect build_packer input
        run: |
          set -euo pipefail
          VAL=$(jq -r '.inputs.build_packer // "false"' "$GITHUB_EVENT_PATH" 2>/dev/null || echo false)
          if [ "$VAL" != "true" ]; then
            echo "Skipping Packer build (build_packer != true)"
            exit 0
          fi

      - name: Generate ephemeral SSH key for template communicator
        run: |
          ssh-keygen -t ed25519 -N "" -C "ci@orchestrate" -f /tmp/ci_key
          echo "SSH_PUBLIC_KEY=$(cat /tmp/ci_key.pub)" >> $GITHUB_ENV

      - name: Packer build template
        env:
          VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
          VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
          VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
          SSH_PUBLIC_KEY: ${{ env.SSH_PUBLIC_KEY }}
        run: |
          packer init packer
          packer build \
            -var "vcenter_server=${VCENTER_SERVER}" \
            -var "vcenter_username=${VCENTER_USERNAME}" \
            -var "vcenter_password=${VCENTER_PASSWORD}" \
            -var "ssh_public_key=${SSH_PUBLIC_KEY}" \
            -var "ssh_private_key_file=/tmp/ci_key" \
            packer/alma-template.pkr.hcl

  terraform:
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    needs: [validate, packer-build]
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          # Ensure Node.js is present for JavaScript-based actions (actions/checkout)
          dnf -y module enable nodejs:20 || true
          dnf -y install unzip curl jq git openssh-clients ca-certificates tar which nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o /tmp/terraform.zip
          unzip -o /tmp/terraform.zip -d /usr/local/bin

      - name: Select environment from inputs
        id: envsel
        run: |
          set -euo pipefail
          ENVIRONMENT=$(jq -r '.inputs.environment // "lab"' "$GITHUB_EVENT_PATH" 2>/dev/null || echo lab)
          if [ "$ENVIRONMENT" = "prod" ]; then
            echo "TF_DIR=terraform/envs/prod" >> "$GITHUB_OUTPUT"
            echo "TF_VARS=prod.tfvars" >> "$GITHUB_OUTPUT"
          else
            echo "TF_DIR=terraform/envs/lab" >> "$GITHUB_OUTPUT"
            echo "TF_VARS=lab.tfvars" >> "$GITHUB_OUTPUT"
          fi

      - name: Terraform init with S3-compatible backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-005
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          set -euo pipefail
          TF_DIR="${{ steps.envsel.outputs.TF_DIR }}"
          if [ -f "$TF_DIR/backend.s3.secrets.hcl" ]; then
            echo "Found local backend.s3.secrets.hcl; using it for init"
            terraform -chdir="$TF_DIR" init \
              -backend-config=backend.hcl \
              -backend-config=backend.s3.secrets.hcl \
              -reconfigure \
              -input=false
          else
            echo "No local backend.s3.secrets.hcl; using CI-provided AWS_* secrets"
            terraform -chdir="$TF_DIR" init \
              -backend-config=backend.hcl \
              -reconfigure \
              -input=false
          fi

      - name: Terraform plan/apply based on input
        env:
          TF_VAR_vsphere_user: ${{ secrets.VSPHERE_USER }}
          TF_VAR_vsphere_password: ${{ secrets.VSPHERE_PASSWORD }}
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-005
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          ACTION=$(jq -r '.inputs.action // "plan"' "$GITHUB_EVENT_PATH" 2>/dev/null || echo plan)
          if [ "$ACTION" = "apply" ]; then
            terraform -chdir=${{ steps.envsel.outputs.TF_DIR }} apply -auto-approve tfplan.out || true
          else
            terraform -chdir=${{ steps.envsel.outputs.TF_DIR }} plan -var-file=${{ steps.envsel.outputs.TF_VARS }} -out=tfplan.out
          fi

  ansible-aap:
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    needs: [terraform]
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          dnf -y install curl jq ca-certificates
      - name: Trigger AAP Job Template (apply only)
        env:
          AAP_URL: ${{ secrets.AAP_URL }}
          AAP_TOKEN: ${{ secrets.AAP_TOKEN }}
          AAP_JOB_TEMPLATE_ID: ${{ secrets.AAP_JOB_TEMPLATE_ID }}
        run: |
          set -euo pipefail
          ACTION=$(jq -r '.inputs.action // "plan"' "$GITHUB_EVENT_PATH" 2>/dev/null || echo plan)
          TARGET_ENV=$(jq -r '.inputs.environment // "lab"' "$GITHUB_EVENT_PATH" 2>/dev/null || echo lab)
          if [ "$ACTION" != "apply" ]; then
            echo "ACTION=$ACTION; skipping AAP trigger (apply only)"
            exit 0
          fi
          if [ -z "$AAP_URL" ] || [ -z "$AAP_TOKEN" ] || [ -z "$AAP_JOB_TEMPLATE_ID" ]; then echo "AAP secrets not set; skipping"; exit 0; fi
          curl -s -X POST "$AAP_URL/api/v2/job_templates/${AAP_JOB_TEMPLATE_ID}/launch/" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $AAP_TOKEN" \
            -d '{"extra_vars": {"target_env": "'"$TARGET_ENV"'"}}' | jq .
