name: orchestrate-push

on:
  push:
    branches:
      - main

jobs:
  kickoff:
    runs-on: [self-hosted, linux, x64, alma]
    steps:
      - name: Emit kickoff
        run: |
          echo "kickoff: ref=${{ github.ref }} sha=${{ github.sha }}"

  validate:
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          # Ensure Node.js is present for JavaScript-based actions (actions/checkout)
          dnf -y module enable nodejs:20 || true
          dnf -y install unzip curl jq git openssh-clients ca-certificates tar which nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes (paths)
        id: changes
        run: |
          set -euo pipefail
          BASE=$(jq -r '.before // ""' "$GITHUB_EVENT_PATH" 2>/dev/null || echo "")
          if [ -n "$BASE" ] && [ "$BASE" != "0000000000000000000000000000000000000000" ]; then
            git fetch --depth=0 origin || true
            git diff --name-only "$BASE" "$GITHUB_SHA" | sort -u > /tmp/changed.txt || true
          else
            git show --pretty="" --name-only "$GITHUB_SHA" | sort -u > /tmp/changed.txt || true
          fi
          touch /tmp/changed.txt
          cat /tmp/changed.txt
          has() { grep -E -q "$1" /tmp/changed.txt; }
          PACKER_CHANGED=false
          TF_CHANGED=false
          ANSIBLE_CHANGED=false
          WORKFLOW_CHANGED=false
          if has '^packer/|\\.pkr\\.hcl$'; then PACKER_CHANGED=true; fi
          if has '^terraform/'; then TF_CHANGED=true; fi
          if has '^ansible/'; then ANSIBLE_CHANGED=true; fi
          if has '^\\.gitea/workflows/'; then WORKFLOW_CHANGED=true; fi
          echo "PACKER_CHANGED=$PACKER_CHANGED" | tee -a "$GITHUB_OUTPUT"
          echo "TF_CHANGED=$TF_CHANGED" | tee -a "$GITHUB_OUTPUT"
          echo "ANSIBLE_CHANGED=$ANSIBLE_CHANGED" | tee -a "$GITHUB_OUTPUT"
          echo "WORKFLOW_CHANGED=$WORKFLOW_CHANGED" | tee -a "$GITHUB_OUTPUT"

      - name: Install Terraform
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o /tmp/terraform.zip
          unzip -o /tmp/terraform.zip -d /usr/local/bin
          terraform -version

      - name: Terraform fmt/validate (lab)
        run: |
          terraform -chdir=terraform/envs/lab init -backend=false
          terraform -chdir=terraform/envs/lab fmt -check
          terraform -chdir=terraform/envs/lab validate

      - name: Terraform fmt/validate (prod)
        run: |
          terraform -chdir=terraform/envs/prod init -backend=false
          terraform -chdir=terraform/envs/prod fmt -check
          terraform -chdir=terraform/envs/prod validate

  terraform:
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    needs: [validate, packer-build]
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          # Ensure Node.js is present for JavaScript-based actions (actions/checkout)
          dnf -y module enable nodejs:20 || true
          dnf -y install unzip curl jq git openssh-clients ca-certificates tar which nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes (paths)
        id: tfchanges
        run: |
          set -euo pipefail
          BASE=$(jq -r '.before // ""' "$GITHUB_EVENT_PATH" 2>/dev/null || echo "")
          if [ -n "$BASE" ] && [ "$BASE" != "0000000000000000000000000000000000000000" ]; then
            git fetch --depth=0 origin || true
            git diff --name-only "$BASE" "$GITHUB_SHA" | sort -u > /tmp/changed.txt || true
          else
            git show --pretty="" --name-only "$GITHUB_SHA" | sort -u > /tmp/changed.txt || true
          fi
          touch /tmp/changed.txt
          has() { grep -E -q "$1" /tmp/changed.txt; }
          PACKER_CHANGED=false
          TF_CHANGED=false
          ANSIBLE_CHANGED=false
          if has '^packer/|\\.pkr\\.hcl$'; then PACKER_CHANGED=true; fi
          if has '^terraform/'; then TF_CHANGED=true; fi
          if has '^ansible/'; then ANSIBLE_CHANGED=true; fi
          echo "PACKER_CHANGED=$PACKER_CHANGED" >> "$GITHUB_ENV"
          echo "TF_CHANGED=$TF_CHANGED" >> "$GITHUB_ENV"
          echo "ANSIBLE_CHANGED=$ANSIBLE_CHANGED" >> "$GITHUB_ENV"

      - name: Install Terraform
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o /tmp/terraform.zip
          unzip -o /tmp/terraform.zip -d /usr/local/bin

      - name: Decide environment from ref (default lab)
        id: envsel
        run: |
          set -euo pipefail
          REF="${GITHUB_REF}"
          ENVIRONMENT="lab"
          case "$REF" in
            refs/heads/orchestrate-prod|refs/tags/orchestrate-prod*) ENVIRONMENT="prod" ;;
            *) ENVIRONMENT="lab" ;;
          esac
          if [ "$ENVIRONMENT" = "prod" ]; then
            echo "TF_DIR=terraform/envs/prod" >> "$GITHUB_OUTPUT"
            echo "TF_VARS=prod.tfvars" >> "$GITHUB_OUTPUT"
          else
            echo "TF_DIR=terraform/envs/lab" >> "$GITHUB_OUTPUT"
            echo "TF_VARS=lab.tfvars" >> "$GITHUB_OUTPUT"
          fi
          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_ENV"

      - name: Decide whether to apply based on ref
        run: |
          set -euo pipefail
          APPLY="false"
          case "${GITHUB_REF}" in
            refs/heads/orchestrate-apply|refs/tags/orchestrate-apply*) APPLY="true" ;;
          esac
          # Auto-apply on lab when Terraform or Packer changes
          if [ "${ENVIRONMENT}" = "lab" ] && { [ "${TF_CHANGED}" = "true" ] || [ "${PACKER_CHANGED}" = "true" ]; }; then
            APPLY="true"
          fi
          echo "APPLY=$APPLY" >> "$GITHUB_ENV"

  packer-build:
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    needs: [validate]
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          # Ensure Node.js is present for JavaScript-based actions (actions/checkout)
          dnf -y module enable nodejs:20 || true
          dnf -y install unzip curl jq git openssh-clients ca-certificates which nodejs

      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes (paths)
        id: pkchanges
        run: |
          set -euo pipefail
          BASE=$(jq -r '.before // ""' "$GITHUB_EVENT_PATH" 2>/dev/null || echo "")
          CHANGED=false
          if [ -n "$BASE" ] && [ "$BASE" != "0000000000000000000000000000000000000000" ]; then
            git fetch --depth=0 origin || true
            if git diff --name-only "$BASE" "$GITHUB_SHA" | grep -E '^packer/|\\.pkr\\.hcl$' -q; then CHANGED=true; fi
          else
            if git show --pretty="" --name-only "$GITHUB_SHA" | grep -E '^packer/|\\.pkr\\.hcl$' -q; then CHANGED=true; fi
          fi
          echo "PACKER_CHANGED=$CHANGED" >> "$GITHUB_ENV"
          echo "PACKER_CHANGED=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Install Packer
        run: |
          curl -fsSL https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip -o /tmp/packer.zip
          unzip -o /tmp/packer.zip -d /usr/local/bin

      - name: Skip if no packer changes
        run: |
          if [ "${PACKER_CHANGED}" != "true" ]; then
            echo "No packer changes; skipping build"
            exit 0
          fi

      - name: Generate ephemeral SSH key for template communicator
        run: |
          ssh-keygen -t ed25519 -N "" -C "ci@orchestrate" -f /tmp/ci_key
          echo "SSH_PUBLIC_KEY=$(cat /tmp/ci_key.pub)" >> $GITHUB_ENV

      - name: Packer build template (on change)
        env:
          VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
          VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
          VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
          SSH_PUBLIC_KEY: ${{ env.SSH_PUBLIC_KEY }}
        run: |
          packer init packer
          packer build \
            -var "vcenter_server=${VCENTER_SERVER}" \
            -var "vcenter_username=${VCENTER_USERNAME}" \
            -var "vcenter_password=${VCENTER_PASSWORD}" \
            -var "ssh_public_key=${SSH_PUBLIC_KEY}" \
            -var "ssh_private_key_file=/tmp/ci_key" \
            packer/alma-template.pkr.hcl

  ansible-aap:
    runs-on: [self-hosted, linux, x64, alma]
    container: almalinux:10
    needs: [terraform]
    steps:
      - name: Prep tools (dnf)
        run: |
          dnf -y makecache
          dnf -y install curl jq ca-certificates
      - name: Trigger AAP Job Template (apply or ansible-only change)
        env:
          AAP_URL: ${{ secrets.AAP_URL }}
          AAP_TOKEN: ${{ secrets.AAP_TOKEN }}
          AAP_JOB_TEMPLATE_ID: ${{ secrets.AAP_JOB_TEMPLATE_ID }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          APPLY: ${{ env.APPLY }}
          ANSIBLE_CHANGED: ${{ env.ANSIBLE_CHANGED }}
        run: |
          set -euo pipefail
          if [ -z "${AAP_URL:-}" ] || [ -z "${AAP_TOKEN:-}" ] || [ -z "${AAP_JOB_TEMPLATE_ID:-}" ]; then echo "AAP secrets not set; skipping"; exit 0; fi
          # Trigger when we applied infra or when only Ansible content changed
          if [ "${APPLY}" = "true" ] || [ "${ANSIBLE_CHANGED}" = "true" ]; then
            TARGET_ENV="${ENVIRONMENT:-lab}"
            curl -s -X POST "$AAP_URL/api/v2/job_templates/${AAP_JOB_TEMPLATE_ID}/launch/" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $AAP_TOKEN" \
              -d '{"extra_vars": {"target_env": "'"$TARGET_ENV"'"}}' | jq .
          else
            echo "No infra apply and no Ansible-only changes; skipping AAP trigger"
          fi

      - name: Terraform init with S3-compatible backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-005
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          set -euo pipefail
          TF_DIR="${{ steps.envsel.outputs.TF_DIR }}"
          if [ -f "$TF_DIR/backend.s3.secrets.hcl" ]; then
            echo "Found local backend.s3.secrets.hcl; using it for init"
            terraform -chdir="$TF_DIR" init \
              -backend-config=backend.hcl \
              -backend-config=backend.s3.secrets.hcl \
              -reconfigure \
              -input=false
          else
            echo "No local backend.s3.secrets.hcl; using CI-provided AWS_* secrets"
            terraform -chdir="$TF_DIR" init \
              -backend-config=backend.hcl \
              -reconfigure \
              -input=false
          fi

      - name: Terraform plan
        env:
          TF_VAR_vsphere_user: ${{ secrets.VSPHERE_USER }}
          TF_VAR_vsphere_password: ${{ secrets.VSPHERE_PASSWORD }}
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-005
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          terraform -chdir=${{ steps.envsel.outputs.TF_DIR }} plan -var-file=${{ steps.envsel.outputs.TF_VARS }} -out=tfplan.out

      - name: Terraform apply (conditional in-shell)
        env:
          TF_VAR_vsphere_user: ${{ secrets.VSPHERE_USER }}
          TF_VAR_vsphere_password: ${{ secrets.VSPHERE_PASSWORD }}
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-005
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          if [ "${APPLY}" != "true" ]; then
            echo "APPLY=false; skipping terraform apply"
            exit 0
          fi
          terraform -chdir=${{ steps.envsel.outputs.TF_DIR }} apply -auto-approve tfplan.out
