---
# Global variables for all environments

# Common settings
pre_update_tasks_enabled: true
post_update_tasks_enabled: true
enable_reboot: true
reboot_timeout: 300
post_reboot_delay: 30

# Notification settings
notification_enabled: true
notification_email: ryan.pampush@gmail.com

# VPS Onboarding
push_user_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICTXfiEHPnR2LHppvnyMUWqp50bV8u01S1td+nFFbjjb"
ansible_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ3O9uVjXALQBplrprCqAWosyVxu+zA0DGUXJw5kJVx7"

# Connection Settings
ansible_user: ansible

# Global firewall settings for all hosts
firewall_management_subnet: "10.37.20.0/24"

# Reverse proxy IPs
firewall_reverse_proxy_ips:
  - "10.37.70.5"
  - "10.37.70.24"

# Safety settings
firewall_rollback_timer: 300
firewall_enable_preflight: true
firewall_enable_validation: true
