---
# Ubuntu-specific variables
debian_updates_apt_cache_valid_time: 3600
debian_updates_apt_upgrade_type: dist # Options: yes, safe, full, dist
debian_updates_apt_autoremove: true
debian_updates_apt_autoclean: true
debian_updates_apt_update_cache_only: false
