---
version: 3

images:
  base_image:
    name: registry.fedoraproject.org/fedora:40

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

options:
  package_manager_path: /usr/bin/dnf
