---
version: 3

images:
  base_image:
    name: almalinux:10

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.18,<2.19
  ansible_runner:
    package_pip: ansible-runner>=2.4,<3.0
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

options:
  package_manager_path: /usr/bin/dnf

additional_build_steps:
  prepend_base: |
    RUN dnf install -y dnf-plugins-core && \
        dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
