---
- name: Include RHEL updates role
  include_role:
    name: rhel_updates
  when: ansible_facts['os_family'] == 'RedHat'

- name: Include Debian updates role
  include_role:
    name: debian_updates
  when: ansible_facts['os_family'] == 'Debian'
