nginxdmz:
  hosts:
    nginx:
dockerhost:
  hosts:
    docker:
cups:
  hosts:
    cupsserver.localdomain:
homeassistant:
  hosts:
    raspberrypi-ha.localdomain:
gameserver:
  hosts:
    linuxgameserver.localdomain:
docker_internal:
  hosts:
    "docker-internal.localdomain":
docker_secure:
  hosts:
    "docker-secure.localdomain":
nginx_internal:
  hosts:
    "nginx-internal.localdomain":
crowdsec_controller:
  hosts:
    "crowdsec.localdomain":
ansible:
  hosts:
    ansible.localdomain:
prusa3dbawkz:
  hosts:
    prusa3dbawkz.localdomain:
opnsense:
  hosts:
    opnsense.localdomain:
      ansible_host: 10.37.70.1
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
